sample_table: resources/test/samples.csv
data: "results"

mincontiglength: 2000 # for binning 

# DBs if set up manually, will be downloaded otherwise
#eukcc2db: "[...]/eukcc2_db_ver_1.1"
#buscodb: "[...]/busco-data.ezlab.org/v5/data"


# sample file
delimiter: "," # delimiter used in the sample table

